### ISSUE TITLE
Criação do banco de dados para salvar antigos Prs

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#105]
## Descrição

A ideia é criar um banco de dados para salvar os antigos PullRequests para o usuário coinseguir comparar com outros
## Objetivos

- [ ] Criar um Banco de dados
- [ ] Criar métodos para acessar o banco de dados, Post e Get para salvar os dados e conseguir utilizar os dados.

## Critérios de Aceitação:

- [ ] Ser possível utilizar os métodos get e post 
- [ ] Construir um json para passar para os metodos

**Comment by ArthurMeloG** [comment]
Estou criando o banco de dados em Low Code, e a documentação esta disponível aqui https://personal-7v9tsjwa.outsystemscloud.com/PullBot_CS/rest/PullbotAPI/#!/PullbotAPI

**Comment by ArthurMeloG** [comment]
talvez, por conta da api do GitHub ser capaz de listar todos os pull requests do repositorio , não há necessidade de salvar em algum lugar, ja que a api é capaz de entregar esses dados

**Comment by eliasyousef00** [comment]
Concordo, não será necessário
