### ISSUE TITLE
Testes unitários

### ISSUE THREAD

**Issue by JaimeJuan11** [fga-eps-mds/MDS-2020-2-G2#107]
## Descrição

Testar as assinaturas de entrada e saída do projeto, afim de validar ou invalidar as aplicações implementadas.

## Objetivos

- [x] Ter conhecimento sobre
- [x] Conseguir implementar no projeto

## Critérios de Aceitação:

- [x] Ter testes unitários para as features

**Comment by JaimeJuan11** [comment]
Foi estudado a tecnologia a ser implementada e foi verificado que a o framework Jest é  uma ótima ferramenta para testes unitários automatizados para a linguagem Javascript

**Comment by zpeniel09** [comment]
Pessoal,mais alguém de você está sem ver o teste:watch na branch? Porque estou tentando executar mas não aparece...

**Comment by zpeniel09** [comment]
Constatei que a branch está duplicado. Sendo assim, encontra-se o teste:watch na branch duplicado.

**Comment by JaimeJuan11** [comment]
A Lorrayne renomeou a branch então provavelmente por isso tenha surgido essa sua dúvida. Dê um 'git checkout master' e depois um 'git checkout 107-testes-unitarios' novamente que deve funcionar.

**Comment by LorrayneCardozo** [comment]
Para realizar os testes, executem o comando: npm run test
