### ISSUE TITLE
Refatoração Protótipo de alta fidelidade

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#113]
## Descrição
Diante das novas implementações, é necessário refatorar o documento para ficar condizente com o escopo do projeto

## Objetivos

- [x] Exemplo ilustrativo - Refatorar 
- [x] Textos explicativos - Refatorar

## Critérios de Aceitação:

- [x] Upload do documento no GitHub pages

**Comment by eliasyousef00** [comment]
Estou fazendo a prototipação das telas (gráficos de desempenho, markdown e popup) do PullBot no figma

**Comment by eliasyousef00** [comment]
Pessoal, o protótipo está pronto!
Já está disponível no github pages. Não esqueçam de conferir
