### ISSUE TITLE
Refatoração do PR automático

### ISSUE THREAD

**Issue by JaimeJuan11** [fga-eps-mds/MDS-2020-2-G2#125]
## Descrição

Diante da reta final do projeto, ajustes serão feitos ao efetuar o PR automático do projeto.

## Objetivos

- [x] Ter uma melhoria no projeto

## Critérios de Aceitação:

- [x] Conseguir efetuar o PR automáticamente

**Comment by LorrayneCardozo** [comment]
ao invés de digitar o nome da branch desejada, o usuário deverá seleciona-lá na lista de branches abertas
![image](https://user-images.githubusercontent.com/78423506/117985728-5365e480-b30f-11eb-8a28-6bd6a16e8b70.png)
