### ISSUE TITLE
Práticas Ágeis

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#13]
# Descrição:  
Estudar as boas práticas e as práticas ágeis para melhorar a desempenho 

# Objetivo:

- [x] Boas Práticas
- [x] Práticas Ágeis

# Critério de Aceitação
- [x] Os outros integrantes do grupo receberem um conteúdo sobre os temas dessa issue

**Comment by LorrayneCardozo** [comment]
Independente da metodologia utilizada, existem algumas práticas indispensáveis para o desenvolvimento ágil do produto, como:
* Ciclos curtos;
* Retrospectivas regulares;
* Colocar o cliente dentro de tudo;
* Simplicidade.

No caso da metodologia ágil Scrum, separamos estes ciclos em Sprints caracterizados por reuniões e entregas frequentes. Também é feito um backlog, que é um conjunto de requisitos que serão entregues em cada Sprint. 
[Fonte](https://www.cin.ufpe.br/~synergy/epf/karua_process/guidances/supportingmaterials/boas_praticas_scrum_B243B70D.html)
