### ISSUE TITLE
GitHub Page

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#15]
# Descrição:  
Criando GitHub Page

# Objetivo:
- [x] Criar documento de visão
- [x] Criar documeteto de arquitetura
- [x] Criar Backlog

# Critério de Aceitação
- [x] Ser possível acessar todas essas áreas no GitHub page

**Comment by eliasyousef00** [comment]
Utilizamos como base o seguinte conteúdo:
https://docsify.js.org/#/?id=docsify

**Comment by ArthurMeloG** [comment]
ótima ideia, coloquei ele em nosso protótipo do GitHub Pages

**Comment by ArthurMeloG** [comment]
Falta ainda adicionar os documentos na página

**Comment by zpeniel09** [comment]
Ficará muito show nosso GitHub Pages quando acabarmos.  :ok_hand:

**Comment by ArthurMeloG** [comment]
Documentos criados e acessíveis
