### ISSUE TITLE
Documento de Arquitetura

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#17]
# Descrição:  
Demonstrar a arquitetura do projeto de software, suas funcionalidades e as decisões de arquitetura durante o desenvolvimento.

# Objetivo:
  - [x] Finalidade do documento
- [x] Escopo
- [x] Referências
- [x] Visão geral
- [x] Representação Arquitetural 
- [x] Plataformas utilizadas
- [x] Metas 

# Critério de Aceitação
- [x] Documento estar pronto com todos os itens acima feitos e revisados por um integrante.

**Comment by eliasyousef00** [comment]
Sugiro que todos os integrantes assistam esses vídeos: 
https://www.youtube.com/watch?v=jUH5lKfpWE0&list=PLkpjQs-GfEMPzOzinFrqfkkfZy2DpwpBh

**Comment by ArthurMeloG** [comment]
Revisado documento de arquitetura, muito bom !
