### ISSUE TITLE
Título do projeto

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#18]
# Descrição:  
Definir o nome para o projeto, aqui nos comentários podemos deixar sugestões 

# Objetivo:
- [x] atribuir um nome para o projeto

# Critério de Aceitação:
- [ ] Renomear nosso repositório

**Comment by ArthurMeloG** [comment]
uma sugestão é  PullBot

**Comment by eliasyousef00** [comment]
PullBot é intuitivo, já que no projeto irá ser feito um pull request com o arquivo .md

**Comment by ArthurMeloG** [comment]
Foi decidido como PullBot
