### ISSUE TITLE
Feedback Semana 3

### ISSUE THREAD

**Issue by francisco1code** [fga-eps-mds/MDS-2020-2-G2#25]
## Feedback Geral
Esse feedback tem como objetivo dar uma orientação e algumas dicas gerais para os membros dessa equipe. No topico **Práticas** irão ser abordado os "pre-requisitos" para cada sprint durante o semestre. Já no topico de **Surgestões de melhorias** irão conter algumas surgestões pessoais para melhor orientar vocês nesse processo.

**Qualquer duvida é só comentar nessa issue, ou também se descorda de algum ponto.**

## Práticas
 - [ ] Quantidade de issues está de acordo com o esperado (pelo menos 1 issue por membro por sprint).
 - [x] As issues estão bem escritas (alguém que não faz parte da equipe é capaz de entender e implementar a solução).
 - [x] Os commits estão atômicos.
 - [ ] Os commits estão bem comentados.
 - [x] O repositório está organizado.
 - [ ] O ritmo do projeto está de acordo com o esperado.
 - [ ] Estão comentando nas issues.
 
## Sugestões de Melhorias
 - [x] Sempre que possivel tentem fechar a issue em seus respectivos prazos, caso contrario, passem ele para o proximo sprint.
 - [x] Tentem começar a fazer as documentações o mais rapido possivel, vocês estão um pouco atrasados em relação ao outros grupos.

 **Revisões de issues**
- #16 #17 Gostei muito dessa issues, boa!,  estão bem detalhadas e bem claras.

**Comment by francisco1code** [comment]
**Documentos de outros projeto que podem usar como base:** [Projeto 1](https://jlucassr.github.io/ArBC-Pages/mds/Documento_de_visao/)  [Projeto 2](https://fga-eps-mds.github.io/2020.2-Hortum)  [Projeto 3](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/documentovisao)

**Comment by ArthurMeloG** [comment]
pode deixar !

**Comment by JaimeJuan11** [comment]
obrigado !

**Comment by ArthurMeloG** [comment]
Documentação adicionada, e foi feito treinamentos para padronizar os commits e os prazos
