### ISSUE TITLE
Definições de mais tecnologias

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#27]
Descrição
- Achei necessário definir mais especificamente as tecnologias utilizadas para o início de nosso protótipo, recomendo a olharem os links que eu vou deixar nos comentários, são muito úteis no nosso projeto.

Objetivos
- [x]  Acessar os sites e esclarecermos como as tecnologias serão implementadas, assim teremos melhor visão do escopo do projeto
- [x] Baixar o Python na máquina e as bibliotecas necessárias

Critério de Avaliação
- [x]  todos integrantes estarem a parte do projeto, as bibliotecas, a documentação da linguagem .
- [x]  Utilizar a IDE definida para Python

**Comment by ArthurMeloG** [comment]
Recomendo utilizarmos o VScode, ele é mais leve que  a maioria das IDEs e tem em MacOs, Windows e as distribuições linux
pesquisei existe a IDE chamada Pycharm pra quem optar, ela é paga, mas da pra criar rapidamente uma conta com o email institucional da UnB e conseguir a licença de estudante  

Para a biblioteca de Python para a API do GitHub, link: https://pygithub.readthedocs.io/en/latest/introduction.html#
nesse site, tem o comando para ser executado no terminal para baixar essa biblioteca, recomendo baixar também a biblioteca de requests

`python -m pip install -U requests`

No canal da IntelliJ tem tutorial da utilização de python, são muito bons !!
outro ponto é sobre o uso de Web services, creio que iremos utilizar, então uma ideia seria o serviço Heroku
link: https://www.heroku.com/

**Comment by ArthurMeloG** [comment]
Para o Python , estou utilizando a última versão 3.9
Quando precisar de ajuda na documentação, a W3schools tem um material muito bem explicado , recomendo
link: https://www.w3schools.com/python/default.asp

**Comment by JaimeJuan11** [comment]
muito bom!!!

**Comment by LorrayneCardozo** [comment]
Como algumas pessoas da equipe nunca tiveram contato com Phyton, o Thonny é uma IDE muito simples feita para iniciantes. Caso alguém se interesse, pode fazer o download ou ler mais sobre [clicando aqui](https://thonny.org/)

**Comment by ArthurMeloG** [comment]
Definida as tecnologias
