### ISSUE TITLE
Documento de visão

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#29]
Documento de visão

## Descrição

Apresentar uma visão geral do PullBot mostrando suas características bem como seus objetivos
## Solução

[Se for um erro, qual o comportamento esperado?]
Na ocorrência de um erro, lançar uma release do documento

## Critérios de Aceitação (se aplicável)

- [ ] Ser publicada aqui e subir o documento para o GitHub pages

**Comment by LorrayneCardozo** [comment]
O documento de visão foi feito e pode ser encontrado [clicando aqui](https://github.com/fga-eps-mds/MDS-2020-2-G2/blob/master/docs/documento_de_visao.md).
