### ISSUE TITLE
Extensão Google Chrome para GitHub

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#30]
Extensão Google Chrome para GitHub

## Descrição

Fornecer um protótipo com o funcionamento mínimo, apenas as funções básicas. Nesse épico, temos que fazer uma extensão que funcione no Google Chrome e responda as features 

FT06 | Pegar evento de fechamento de milestone automaticamente

FT07 | Acessibilzar extensão no Chrome

**Comment by eliasyousef00** [comment]
o principal arquivo para criação de uma extensão é o manifest.json()
