### ISSUE TITLE
Adicionar sprints no GitHub Pages

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#34]
# Nome da Issue

## Descrição

Atualização do site com as sprints organizadas

## Critérios de Aceitação (se aplicável)

- [x] Ser possível visualizar as sprints com seus respectivos conteúdos

**Comment by eliasyousef00** [comment]
A documentação das sprints está devidamente atualizada

**Comment by JaimeJuan11** [comment]
As documentações estão sendo atualizadas semanalmente.
