### ISSUE TITLE
Comunicação Git via API

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#37]
## Descrição
Início da aplicação, importar as bibliotecas necessárias e iniciar o request via API

## Solução

Acesso via token do GitHub

## Critérios de Aceitação (se aplicável)

- [x]  Ser possível se comunicar com o Git e interagir com o git

**Comment by ArthurMeloG** [comment]
Realizei a comunicação com o Git via token, para isso, precisamos usar variáveis de ambiente parra garantir a segurança

**Comment by eliasyousef00** [comment]
Precisamos utilizar o método POST (responsável por enviar as informações) e ter acesso ao token para realizar ações em um repositório

**Comment by zpeniel09** [comment]
Pessoal  para abrirmos um Pull Request via GitHub API precisamos de alguns passos para incluir no nosso software por isso,minha dupla e eu gostariamos de saber se vocês conseguem um retorno ao executar  este comando no terminal de vocês:
npm install --save-dev @octokit/core
 Se sim,passem para nós o retorno que tiveram o mais rapido possível.
