### ISSUE TITLE
Redefinição de tecnologia para JavaScript

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#40]
Redefinição de tecnologia para JavaScript

- Descrição 
-  Ao implementar as funcionalidades de API em python, foi discutido a viabilidade de utilizarmos javascript.

  
´- Critérios de avaliação 
- [x] Para critério de aceitação, todos devem comentar que concordam .

**Comment by eliasyousef00** [comment]
De fato, JavaScript seria uma tecnologia mais adequeda.

**Comment by LorrayneCardozo** [comment]
Concordo que JavaScript seja uma tecnologia mais apropriada.
