### ISSUE TITLE
Identificar botão de close de milestone

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#44]
O botão de fechamento de milestone (close)

Não possui id próprio ou classe específica, precisamos achar uma forma de pegar seu evento click

Considerei pegar um array com sua classe e filtrar por ele

Critérios de avaliação

- [x] Ser possível identificar o botão via Js

**Comment by eliasyousef00** [comment]
O botão está dentro de uma tag <form> que tem como class="d-inline-block mr-2". O botão é o único <button> dentro do form, então podemos acessa-lo via JS utilizando o query selector.
