### ISSUE TITLE
Refatoração Backlog

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#50]
Backlog precisa ser refatorado

Alguns itens desnecessários no markdown e informações faltando

- [x] Arrumar markdown quebrado
- [x] Adicionar Hidtórico de versões 
- [x] Refatorar features
- [x] Refatorar Épicos
- [x] Refatorar US

- Critérios de avaliação 

- [x]  Backlog atualizado e revisado por integrantes no site

**Comment by ArthurMeloG** [comment]
Lancei alguns épicos novos mais direcionados e com a tentativa de serem mais claros ao visitante da página e aos developers

**Comment by ArthurMeloG** [comment]
Algumas features foram incorporadas no backlog, quem puder dar uma olhada, tem algumas ideias bem interessantes

**Comment by ArthurMeloG** [comment]
User stories mais claras e objetivas , com as features a serem implementadas

**Comment by eliasyousef00** [comment]
Os épicos, Features e User Stories estão de acordo com o escopo do projeto.

**Comment by ArthurMeloG** [comment]
Refeito o backlog no dia 17/03/2021

**Comment by ArthurMeloG** [comment]
De acordo com o FeedBack 5, irei refatorar o épico 03
