### ISSUE TITLE
Refatoração do documento de arquitetura

### ISSUE THREAD

**Issue by eliasyousef00** [fga-eps-mds/MDS-2020-2-G2#51]
O documento de arquitetura necessita passar por uma reformulação. 
Existem algumas informação erradas, erros de markdown e falta de informações.

- [x] Arrumar erros de markdown
- [x] Adicionar tecnologias utilizadas e suas respectivas descrições
- [x] Adicionar partes faltantes
- [x] Concerto dos demais erros

- Critério de valiação
- [x] Revisão do documento por integrante do grupo

**Comment by ArthurMeloG** [comment]
Essa arquitetura é interessante https://developer.chrome.com/docs/extensions/mv2/architecture-overview/

**Comment by LorrayneCardozo** [comment]
Também gostei dessa arquitetura! Acredito que dará certo no nosso projeto

**Comment by zpeniel09** [comment]
A correção sobre o documento de arquitetura foi feito!

**Comment by JaimeJuan11** [comment]
Demanda finalizada
