### ISSUE TITLE
Desenvolvimento do protótipo de alta fidelidade

### ISSUE THREAD

**Issue by eliasyousef00** [fga-eps-mds/MDS-2020-2-G2#55]
O protótipo de alta fidelidade precisa ser desenvolvido e disponibilizado no github pages

- [x] Desenvolvimento do corpo do documento
- [x] Descrição das funcionalidades do projeto
- [x] Disponibilizar no github pages

Critérios de aceitação:

- [x] Ser revisado por um membro do grupo

**Comment by JaimeJuan11** [comment]
Revisado e aprovado!
