### ISSUE TITLE
Refatoração do documento de visão

### ISSUE THREAD

**Issue by LorrayneCardozo** [fga-eps-mds/MDS-2020-2-G2#60]
# Refatoração do documento de visão

## Descrição

Após algumas mudanças no decorrer do desenvolvimento do projeto, algumas alterações no documento de visão se tornaram necessárias.

## Critérios de Aceitação (se aplicável)

- [x] Avaliação dos demais integrantes da equipe

**Comment by JaimeJuan11** [comment]
Conferido e mergeado!
