### ISSUE TITLE
Apresentação para a Release 1

### ISSUE THREAD

**Issue by JaimeJuan11** [fga-eps-mds/MDS-2020-2-G2#64]
## Descrição

Realizar apresentação para a _Release 1_

## Objetivos

- [x] Ter a apresentação pronta
- [x] Ter todos os documentos prontos

## Critérios de Aceitação:

- [x] Documentações revisadas
- [x] GitHub-Pages revisado
- [x] Repositório revisado

**Comment by JaimeJuan11** [comment]
demanda realizada

**Comment by RochaCarla** [comment]
Onde estão os Links? qual a evidencia da realização da issue?

**Comment by JaimeJuan11** [comment]
os links foram devidamente colocados às 20h15
