### ISSUE TITLE
Revisão documentaçao R1

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#66]
## Descrição

Fazer uma breve revisçao de documentação para a entrega da release 1

## Objetivos

- [x] Revisar Readme
- [x]  Revisar Documento de arquitetura
- [x]  Revisar Backlog 
- [x] Revisar documento de visão
- [x] Revisar especificação suplementar
- [x] Revisar protótipo de baixa fidelidade
- [x] Revisar protótipo de alta fidelidade
- [x] Revisar roadmap
- [x] Revisar TAP

## Critérios de Aceitação:

- [ ] Os ibtegrantes derem o feadback aqui quanto aos itens revisados

**Comment by JaimeJuan11** [comment]
Demanda realizada.
