### ISSUE TITLE
Estudar Git

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#7]
Descrição:

- [x] Estudar Git e seus comandos.

Objetivo:

- [x] Aprender os comandos e como utilizar o GitHub de maneira eficiente.

Critério de Aceitação:

- [ ] Todos integrantes conseguirem comentar nessa issue.

**Comment by ArthurMeloG** [comment]
para estudarmos git temos o treinamento feito pelos monitores durante a primeira sprint. É um material de ótima qualidade

**Comment by eliasyousef00** [comment]
Fiz o treinamento. Acredito que já estou pronto pra colocar em prática no projeto.
