### ISSUE TITLE
Definir tecnologias a serem utilizadas 

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#8]
Após definido o tema, analisar qual melhor será tecnologia para o projeto.

**Comment by zpeniel09** [comment]
Levando em consideração o Feedback semana 1 #14  dado por  @francisco1code será preciso que unirmos o #10 com as tecnologias a serem utilizadas.
**Porém estamos definindo(quase pronto) já as que vamos usar para o projeto.**

**Comment by ArthurMeloG** [comment]
Precisamos redefinir as tecnologias pois avaliamos as tecnologias antes do tema proposto, sugiro estudarmos tecnologias viáveis para a criação de um bot

**Comment by eliasyousef00** [comment]
Pesquisei sobre as melhores tecnologias para o desenvolvimento e acredito que Python pode ser a melhor opção pra isso. Achei muito exemplos na internet de bots construidos com python e em diversas plataformas (Discord, Telegram, Whatsapp...)

**Comment by ArthurMeloG** [comment]
python me parece uma boa ideia, vi em projetos antigos que ele é bastante utilizado
