### ISSUE TITLE
Estudo de viabilidade de banco de dados

### ISSUE THREAD

**Issue by JaimeJuan11** [fga-eps-mds/MDS-2020-2-G2#83]
## Descrição

Estudar a viabilidade de implementação de banco de dados no projeto

## Objetivos

- [ ] Achar um banco de dados que se encaixe

## Critérios de Aceitação:

- [ ] Ter estudado mais de uma opção de banco de dados

**Comment by zpeniel09** [comment]
- Entre todos os modelos de Dados faremos uso do modelo Relacional no nosso projeto. Esse modelo consiste em ter uma visão clara de como os dados serão guardados no BD. 
- Com esse modelo podemos organizar os dados em coleção de tabelas bidimensionais.
- Essas tabelas recebem nome de ralações.
-  Sendo assim usaremos o Banco de Dados Relacional(Um banco de Dados criado a partir desse modelo relacional).

**Comment by ArthurMeloG** [comment]
interessante, vou analisar esses pontos

**Comment by zpeniel09** [comment]
- O banco em questão que faremos uso será o MySQL.
