### ISSUE TITLE
Correção de bug

### ISSUE THREAD

**Issue by JaimeJuan11** [fga-eps-mds/MDS-2020-2-G2#84]
## Descrição do bug
Pull request está funcionando somente no segundo evento close de milestone

## Como repetir o bug:
Passos para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Desça a tela até '....'
4. Veja o erro
5. ........

## Comportamento esperado:
Descreva o que era esperado acontecer

## Screenshots:
Se aplicável, adicione screenshots para ajudar a explicar seu problema.

**Comment by ArthurMeloG** [comment]
Apos algumas analises notamos que o bug s=surge quando tem a extensão do google tradutor junto com o pullbot, mas arrumamos isso com a página que surge quando apertamos o close do botao
