### ISSUE TITLE
Organizar arquitetura do projeto

### ISSUE THREAD

**Issue by JaimeJuan11** [fga-eps-mds/MDS-2020-2-G2#85]
## Descrição

Grande parte do projeto encontra-se somente no arquivo index.js, assim sendo é necessário uma melhor organização arquitetural

## Objetivos

- [ ] Distribuir o código em mais de um arquivo

## Critérios de Aceitação:

- [ ] Criar um arquivo services.js

**Comment by ArthurMeloG** [comment]
Fizemos as alterações necessarias e um arquivo para métodos, a ideia é sempre melhorar a organização, mas acredito que estamos no caminho certo, sendo assim fecharei a issue pois aprendemos como organizar nossos arquivos
