### ISSUE TITLE
Criar retorno em markdown ao fechamento do pull request automático

### ISSUE THREAD

**Issue by JaimeJuan11** [fga-eps-mds/MDS-2020-2-G2#86]
## Descrição

Criar retorno de mensagem em markdown ao fechamento do pull request automático

## Objetivos

- [x] Conseguir retornar uma mensagem em markdown com informações úteis

## Critérios de Aceitação:

- [x] Conseguir retornar uma mensagem em markdown

**Comment by LorrayneCardozo** [comment]
após fechar a milestone, será aberto um modal para que o usuário insira as seguintes informações sobre o pull request:
![image](https://user-images.githubusercontent.com/78423506/114231882-6ae93080-9951-11eb-959d-4754fe06c441.png)

**Comment by LorrayneCardozo** [comment]
o pull request automático terá o seguinte escopo:
![image](https://user-images.githubusercontent.com/78423506/114234567-560e9c00-9955-11eb-86d5-8e494f963a8d.png)
