### ISSUE TITLE
Estudo de tecnologia para geração de gráficos informativos

### ISSUE THREAD

**Issue by JaimeJuan11** [fga-eps-mds/MDS-2020-2-G2#87]
## Descrição

Estudo de tecnologia para geração de gráficos informativos após fechamento de milestone

## Objetivos

- [ ] Achar uma tecnologia viável ao projeto

## Critérios de Aceitação:

- [x] Estudar mais de uma opção de tecnologia

**Comment by eliasyousef00** [comment]
Pessoal, existem diversas bibliotecas que podem atender a nossa necessedade. Entre elas estão:
1 - Google Charts
2 - Charts.js
3 - Chartist.js
4 - HighCharts js
5 - FusionCharts
6 - D3.js
