### ISSUE TITLE
Estudar sobre práticas ágeis no desenvolvimento

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#9]

**Comment by zpeniel09** [comment]
Depois do meu estudo sobre práticas ágeis no desenvolvimento vai aqui um link com qual vocês terão acesso a um rápido resumo: [clique aqui](https://www.devmedia.com.br/fundamentos-das-metodologias-ageis/22527) e para mais informação eu enviei um artigo para meus colegas falando mais sobre o tema.
