### ISSUE TITLE
Implementação do banco de dados

### ISSUE THREAD

**Issue by JaimeJuan11** [fga-eps-mds/MDS-2020-2-G2#91]
## Descrição

Implementar no projeto um banco de dados que se encaixe de forma a salvar as informações do token e do device id.

## Objetivos

- [ ] Conseguir implementar o banco de dados no projeto.
- [ ] Conseguir com que o banco de dados salve as informações do token e do device id.

## Critérios de Aceitação:

- [ ] Estar funcional e operante.

**Comment by zpeniel09** [comment]
Após algumas conversas com os menbros do grupo,constatamos que não seria necessario(Outras tecnicas foram usados) porém assim que for preciso isso será implementado.
