### ISSUE TITLE
Aprimoramento do layout da extensão da API

### ISSUE THREAD

**Issue by JaimeJuan11** [fga-eps-mds/MDS-2020-2-G2#92]
## Descrição

Aprimoramento do layout da extensão da API no navegador, onde será reestruturado a tela apresentada ao usuário.

## Objetivos

- [ ] Deixar o layout da extensão mais intuitivo.

## Critérios de Aceitação:

- [ ] Layout reestruturado com uma nova "cara".

**Comment by eliasyousef00** [comment]
Adicionei textos explicativos a respeito do PullBot e estilizei tudo isso.
