### ISSUE TITLE
Geração de gráficos informativos por contribuinte

### ISSUE THREAD

**Issue by ArthurMeloG** [fga-eps-mds/MDS-2020-2-G2#96]
## Descrição da feature
Para aprimoramento do bot, desejamos que ele entregue graficos com informações valiosas sobre o desenpenho pessoal.

## Objetivo:
- [ ] Graficos Intuitivos
- [ ] Graficos de commits 
- [ ] Interação nas issues

## Critérios de Aceitação:
- [ ] Ser possível gerar o grafico com os objetivos propostos para qualquer contribuinte do repositorio

**Comment by eliasyousef00** [comment]
Não vamos conseguir usar a biblioteca pdfmake para gerar os pdfs, pois ela utiliza o método eval(), que torna a aplicação insegura, abrindo possibilidade para ataques e possíveis malwares.

**Comment by eliasyousef00** [comment]
podemos buscar por outras bibliotecas que não utilizem o método eval e consigam gerar nos PDFs com as imagens dos gráficos.

**Comment by eliasyousef00** [comment]
achei uma forma viável de conseguir gerar os PDFs. Basicamente, se conseguirmos converter a tag canvas do html em svg, a geração dos PDFs fica mais tranquilo.

**Comment by eliasyousef00** [comment]
Testei vários métodos e bibliotecas, mas não tem jeito, todas elas utlizam o método eval. Se quisermos gerar os PDFs com gráficos informativos, então vamos ter que utilizar o SandBox na extensão.
Dêem uma olhada em: https://developer.chrome.com/docs/extensions/mv2/sandboxingEval/
