### ISSUE TITLE
Implementação da biblioteca chartJS

### ISSUE THREAD

**Issue by JaimeJuan11** [fga-eps-mds/MDS-2020-2-G2#97]
## Descrição

Implementação da biblioteca chartJS que é uma biblioteca JavaScript de código aberto gratuita para visualização de dados, que suporta 8 tipos de gráficos: barra, linha, área, pizza, bolha, radar, polar e dispersão; que muito será útil para o projeto.

## Objetivos

- [x] Implementar a biblioteca chartJS
- [x] Fazer com que seja possível implementar os resultados por gráfico

## Critérios de Aceitação:

- [x] Passar nos testes

**Comment by zpeniel09** [comment]
O feedback sobre o PR que a professora passou será levado em consideração nas proxímas etapas por motivo que essa issue já foi mergeado(Essa issue era necessário para as outras issues). Sendo assim estarei fechando esta issue.
